variables:
  REPO_NAME: gitlab.com/mironet/exim-relay-docker

stages:
    - build
    - release

# Build app.
build-app:
  stage: build
  image: docker:19
  before_script:
    - apk add --no-cache git
    - git --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export GIT_TAG=$(git describe --always)
    - export DOCKER_BUILDKIT=1
  script:
    - echo $GIT_TAG
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE"

# Build app.
build-tagged-app:
  stage: build
  image: docker:19
  before_script:
    - apk add --no-cache git
    - git --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export GIT_TAG=$(git describe --always)
    - export DOCKER_BUILDKIT=1
  script:
    - echo $GIT_TAG
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$GIT_TAG" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$GIT_TAG"
    - docker tag "$CI_REGISTRY_IMAGE:$GIT_TAG" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
  - /v[0-9|\.]+-?[0-9A-Za-z-]*/
